package TELAS;

import dao.CadastroDao2;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Panel;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import modelo.Cadastro;
import modelo.Sexualidade;
import modelo.Profissao;
import TELAS.cadastrouser;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import dao.SexualidadeDao;
import dao.ProfissaoDao;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author leona
 */
public class jfDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form jfDashBoard
     */
    public jfDashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        barPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pizzaPanel = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tb01 = new javax.swing.JTable();
        jbCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Número de cadastros válidos");

        jPanel11.setBackground(new java.awt.Color(255, 255, 204));

        barPanel.setBackground(new java.awt.Color(255, 255, 204));
        barPanel.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setText("GRÁFICOS");

        pizzaPanel.setBackground(new java.awt.Color(255, 255, 204));
        pizzaPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(barPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pizzaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pizzaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(barPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );

        jButton4.setText("MENU");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Tb01.setForeground(new java.awt.Color(0, 153, 255));
        Tb01.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "CPF", "Sexo", "Profissão", "Cep"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tb01.setGridColor(new java.awt.Color(0, 153, 255));
        Tb01.setShowGrid(false);
        Tb01.setShowHorizontalLines(true);
        Tb01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb01MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tb01);
        if (Tb01.getColumnModel().getColumnCount() > 0) {
            Tb01.getColumnModel().getColumn(0).setMaxWidth(25);
        }

        jbCadastrar.setText("NOVO CADASTRO");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jbCadastrar))
                        .addGap(49, 49, 49))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tb01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb01MouseClicked
        // TODO add your handling code here:
        if (Tb01.getSelectedRow() != -1) {

            Cadastro cadastro = new Cadastro();

            cadastro.setIdCadastro(Integer.parseInt(Tb01.getValueAt(Tb01.getSelectedRow(), 0).toString()));
            cadastro.setNomeCadastro(Tb01.getValueAt(Tb01.getSelectedRow(), 1).toString());
            cadastro.setCpf(Tb01.getValueAt(Tb01.getSelectedRow(), 2).toString());
            cadastro.SetNomeSexo(Tb01.getValueAt(Tb01.getSelectedRow(), 3).toString());
            cadastro.SetNomeProfissao(Tb01.getValueAt(Tb01.getSelectedRow(), 4).toString());
            cadastro.setCep(Tb01.getValueAt(Tb01.getSelectedRow(), 5).toString());
            cadastrouser frmCad = new cadastrouser();
            frmCad.exportardados(cadastro);
            frmCad.setVisible(true);
        }
    }//GEN-LAST:event_Tb01MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        new cadastrouser().setVisible(true);

    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        CadastroDao2 cadastroDao2 = new CadastroDao2();
        atualizaDash(cadastroDao2);
        atualizaTabela(cadastroDao2);
    }//GEN-LAST:event_formWindowGainedFocus
    private void atualizaDash(CadastroDao2 cadastroDao2) {
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    try {

                        ArrayList<Cadastro> listaCadastros;
                        listaCadastros = cadastroDao2.dashboard();

                        DefaultCategoryDataset barChartData = new DefaultCategoryDataset();

                        DefaultPieDataset pizzaChartData = new DefaultPieDataset();

                        for (Cadastro cadastro : listaCadastros) {

                            // Adiciona dados ao gráfico de barras
                            barChartData.setValue(cadastro.getCadastroUsuarios(), "Cadastro Usuarios", "Cadastro Usuarios");
                            barChartData.setValue(cadastro.getAtualizacao(), "Atualizacao", "Atualizacao");
                            barChartData.setValue(cadastro.getDeletes(), "Deletes", "Deletes");

                            // Adiciona dados ao gráfico pizza
                            pizzaChartData.setValue("Cadastro Usuarios", cadastro.getCadastroUsuarios());
                            pizzaChartData.setValue("Atualizacao", cadastro.getAtualizacao());
                            pizzaChartData.setValue("Deletes", cadastro.getDeletes());

                        }
                        //Gráfico em barras
                        JFreeChart barChart = ChartFactory.createBarChart("Ex Barras", "Dados", "Valores", barChartData,
                                PlotOrientation.VERTICAL, true, true, false);
                        CategoryPlot barchrt = barChart.getCategoryPlot();
                        barchrt.setRangeGridlinePaint(new Color(140, 105, 204));
                        ChartPanel ChartP = new ChartPanel(barChart);
                        barPanel.removeAll();
                        barPanel.add(ChartP, BorderLayout.CENTER);
                        barPanel.validate();

                        //Gráfico em pizza
                        JFreeChart pizzaChart = ChartFactory.createPieChart("Ex: Pizza", pizzaChartData);
                        PiePlot pizzachrt = (PiePlot) pizzaChart.getPlot();
                        ChartPanel ChartPizza = new ChartPanel(pizzaChart);
                        pizzaPanel.removeAll();
                        pizzaPanel.add(ChartPizza, BorderLayout.CENTER);
                        pizzaPanel.validate();

                        Thread.sleep(500);

                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", ERROR_MESSAGE);
                    }
                }
            }
        }.start();
    }

    private void limparTabela() {
        //percorre a tabela e exclui todas as linhas
        while (Tb01.getRowCount() > 0) {
            DefaultTableModel dm = (DefaultTableModel) Tb01.getModel();
            dm.getDataVector().removeAllElements();
        }
    }

    private void atualizaTabela(CadastroDao2 cadastroDao2) {
     

                try {

                    limparTabela();

                    ArrayList<Cadastro> listaCadastros;
                    listaCadastros = cadastroDao2.consultar(); //consulta todos os registros da tabela Escola

                    //Resgata o modelo da tabela            
                    DefaultTableModel modeloTabela = (DefaultTableModel) Tb01.getModel();

                    for (Cadastro cadastro : listaCadastros) {
                        //adiciona em cada linha da tabela da tela o conteúdo de cada posição da listaEscolas
                        modeloTabela.addRow(new String[]{Integer.toString(cadastro.getIdCadastro()),
                            cadastro.getNomeCadastro(),
                            cadastro.getCpf(),
                            cadastro.getNomeSexo(),
                            cadastro.getNomeProfissao(),
                            cadastro.getCep()
                        });
                    }

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", ERROR_MESSAGE);
                }
            
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tb01;
    private javax.swing.JPanel barPanel;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JPanel pizzaPanel;
    // End of variables declaration//GEN-END:variables
}
